version: "3"

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mongo
    networks:
      - host
  mongo:
    image: mongo
    ports:
      - 27017:27017 
    networks:
      - host
    environment:
      - MONGO_INITDB_DATABASE=main
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

    volumes:
       - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

networks:
  host:
